### ISSUE TITLE
add an option to lookup lat/lon

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/config.berlin.freifunk.net#23]
The user should configure a lat/lon in the freifunk assistent. If we provide an option to lookup the lat/lon coordinates in config.berlin.freifunk.net we can add this to the mail template with the ip information etc. and the user can copy this information into the assistant.

**Comment by cholin** [comment]
I tried to minimize data collection for config.berlin.freifunk.net. I think lat/lon data is not vital for a working node but maybe with the new wizard (https://github.com/freifunk-berlin/firmware-wizard-frontend) we could discuss this again.
