### ISSUE TITLE
TL-WR841ND == TL-WR841N?

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/config.berlin.freifunk.net#32]
A user of the firmware told me that he successfully flashed a TL-WR841ND with the TL-WR841N firmware. The "D" usually simply indicates that the antenna is detachable. Maybe we can place a "(D)" to all TL-WR841N models?

**Comment by booo** [comment]
They are the same I guess: http://wiki.openwrt.org/toh/tp-link/tl-wr841nd

**Comment by cholin** [comment]
Can you be a bit more precise? Except detachable antennas the firmware differs for different versions (v3, v5, v7, v8, v9) for TL-WR841. What firmware has the person flashed on what device?

**Comment by andrenarchy** [comment]
I don't know the exact revision but I think that it actually doesn't matter because there seem to be D-versions of all revisions (see [here](http://wiki.openwrt.org/toh/tp-link/tl-wr841nd) right before the *failsafe mode* section). Thus, I think we should add the "D" for all revisions if only the antennas differ.

**Comment by SvenRoederer** [comment]
upstream all manes have been changed to the same suffix.
With freifunk-berlin/firmware#286 this will be obsolete and can explained in the wiki-pages

**Comment by sarumpaet** [comment]
obsoleted by 868aa00
