### ISSUE TITLE
Feedback on potential pynipap improvements

### ISSUE THREAD

**Issue by plajjan** [freifunk-berlin/config.berlin.freifunk.net#34]
Hey guys, 

so this isn't much of an issue or feature request on this project in itself. Instead I would like to encourage that you open issues / PRs for improvements on pynipap.

I've skimmed through https://github.com/freifunk-berlin/config.berlin.freifunk.net/blob/master/app/nipap.py and find that are a few functions, like get_pool_by_name or get_vrf_by_name, that are wrapping around pynipap that shouldn't really need to be wrapped at all - it should be offered by pynipap straight away.

I would like your feedback on how we can enhance pynipap in such a way that you, and others, don't have to write as much wrapper code to get started with pynipap :)

   //kll

**Comment by cholin** [comment]
Sorry I seem to have missed this issue. You're right that these function should be offered by pynipap. My time is limited at the moment but I try to give you some feedback in the next days/weeks.

**Comment by Akira25** [comment]
closed due inactivity.
