### ISSUE TITLE
allow to request IP-addresses out of the Mesh-range

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/config.berlin.freifunk.net#39]
it seems there is no official way to request "Mesh"-only Ip-addresses from the reserved Mesh-addressrange 10.31.0.0/16. 
Using the IP-Expert you will only get addresses from 10.230.0.0/16 (maybe 10.36.0.0/16) which are reserved for DHCP-clients. see http://lists.berlin.freifunk.net/pipermail/berlin/2015-November/030789.html .

Mesh-only hosts are usefull when Routers are connected via OLSR and using B.A.T.M.A.N. (via LAN) to have a singe DHCP-server.

**Comment by booo** [comment]
There is no strict definition of a mesh ip range and a dhcp ip range. IPs are like names "Schall und Rauch". Once one pool is empty we need to use the other "range" for dhcp too.

**Comment by SvenRoederer** [comment]
As Bastian was mentioning this kind of reservation in "http://lists.berlin.freifunk.net/pipermail/berlin/2015-November/030793.html".

But when it's more like "nice to have" these ranges, we should put our focus on other things than IP-address-plans
