### ISSUE TITLE
Make HTTPS mandatory

### ISSUE THREAD

**Issue by sarumpaet** [freifunk-berlin/config.berlin.freifunk.net#41]
Neither config.berlin.freifunk.net nor ca.berlin.freifunk.net use mandatory HTTPS despite actual user data getting transmitted. Also, both should set HSTS and X-Frame-Options headers.

```
add_header Strict-Transport-Security max-age=31536000;
add_header X-Frame-Options "SAMEORIGIN";
```

**Comment by booo** [comment]
Thanks for pointing this out and assigning me ;)

Should we fix this with a permanent redirect?

I actually prefer to open operation tickets in https://github.com/freifunk-berlin/puppet/issues

If someone wants to fix it without puppet I volunteer to transfer simple changes to puppet after they are made on the server.

**Comment by sarumpaet** [comment]
Sure, a permanent redirect plus the two headers I mentioned above. It'd be good if you could adjust the puppet scripts.
