### ISSUE TITLE
replace tl-cpe210.jpg with tl-cpe210-v1.jpg

### ISSUE THREAD

**Issue by ber-red** [freifunk-berlin/config.berlin.freifunk.net#42]
**cosmetic issue only:**
I would suggest to replace 
`config.berlin.freifunk.net/app/static/img/router/tl-cpe210.jpg`
which is pointing to kathleen firmware within 
`config.berlin.freifunk.net/default.cfg`
with an image clearly pointing out "v1" HW Revision

This will make the site more consistent and hopefully this will help newbies to avoid buying Hardware not already supported, or at least let them ask for matching builds for v1.1 via mailing list?!
See also [here](https://github.com/freifunk-berlin/berlin.freifunk.net/issues/51).

**Comment by SvenRoederer** [comment]
this will be obsolete with https://github.com/freifunk-berlin/firmware/issues/286

**Comment by sarumpaet** [comment]
obsoleted by 868aa00
