### ISSUE TITLE
Every request results in 500 Internal Server Error

### ISSUE THREAD

**Issue by freerko** [freifunk-berlin/config.berlin.freifunk.net#44]
With both wizard and expert mode it is not possible to request a new IP. 
The server responds with a "500 Internal Server Error" in the last step.

**Comment by SvenRoederer** [comment]
Bitte nochmal prüfen, soll jetzt wieder funktionieren.

Ein paar aktualisierte Softwarepakete haben sich da gebissen

**Comment by booo** [comment]
Should work again. I'm closing this. Thanks for reporting the problem!

Side note: Someone should update the nipapd application and database.
