### ISSUE TITLE
EMail address should be case insensitive

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/config.berlin.freifunk.net#47]
in https://config.berlin.freifunk.net/summary sollte es keine Rolle spielenwelcher mix von Groß- und Kleinbuchstaben für eine EMail-Adresse genutzt wird. Es heute ja üblich, dass jede Schreibweise zum gleichen EMail-account führt.

"Freifunk@my-domain" gibt 1 registrierte Adresse zurück
"freifunk@my-domain" gibt >10 registrierte Adressen zurück

**Comment by SvenRoederer** [comment]
Das betrifft auch die Funktion der Adressrückgabe

**Comment by rtznprmpftl** [comment]
yes/no/maybe ;-)

the domain should be case insensitive, the local part not:


https://datatracker.ietf.org/doc/html/rfc5321#section-2.3.11


```
   Consequently, and due to a
   long history of problems when intermediate hosts have attempted to
   optimize transport by modifying them, the local-part MUST be
   interpreted and assigned semantics only by the host specified in the
   domain part of the address.
```

**Comment by nicolasberens** [comment]
we currently have about 30 adresses affected by this behaviour.

`select count(distinct(email)) from ip_request; ` vs `select count(distinct(LOWER(email))) from ip_request; `

**Comment by nicolasberens** [comment]
Code changes:

**THIS IS UNTESTED!**

Most likely we could just change:
https://github.com/freifunk-berlin/config.berlin.freifunk.net/blob/master/app/forms.py 

And replace all occurances of:` email = StringField("E-Mail", validators=[Email()]) ` with `email = StringField("E-Mail", validators=[Email()]).lower()`


The Wizard db :
`UPDATE ip_request SET email=lower(email)`
nipap:

`UPDATE ip_net_plan SET customer_id=lower(customer_id) WHERE customer_id LIKE '%@%';`



When working on this we should also check if all users in the wizard db have an entry in nipap and vice versa.

**Comment by nicolasberens** [comment]
fixed in pr #95
