### ISSUE TITLE
can't receive IP adresses

### ISSUE THREAD

**Issue by hardyhase** [freifunk-berlin/config.berlin.freifunk.net#49]
Hey, I don't become IP adresses at my E-Mail. Is there a failure in the system https://config.berlin.freifunk.net/?

**Comment by fmanzke** [comment]
I'm receiving "Internal Server Error" after submitting the form and I don't receive any confirmation email.

**Comment by booo** [comment]
Thanks for reporting. We did a system upgrade and after the upgrade the setup of the nipap database wasn't complete.

I executed:

```
psql -d nipap -f /usr/share/nipap/sql/ip_net.plsql
psql -d nipap -f /usr/share/nipap/sql/functions.plsql
psql -d nipap -f /usr/share/nipap/sql/triggers.plsql
```

Just executing `CREATE EXTENSION ip4r;` is not enough.

**Comment by booo** [comment]
Should work again ;)
