### ISSUE TITLE
Add /23 and /22 to options in expert mode

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/config.berlin.freifunk.net#50]
In _hopefully_ extremely rare circumstances it is necessary to have more than a /24 DHCP network.  It would be quite useful to be able to request a /23 or /22 network.

Currently it is possible to be lucky and to get two consecutive /24 addresses which can be combined into a larger /23.  But this is impractical.

**Comment by pmelange** [comment]
I believe that this is the only place where a change would be needed.  @booo, what do you think:

https://github.com/freifunk-berlin/config.berlin.freifunk.net/blob/31d0acc4358247b3418a58c1c9b946f5eb878e97/default.cfg#L18

**Comment by rtznprmpftl** [comment]
this already works in prod.

==> close
