### ISSUE TITLE
confirmation-mail: no link for deactivation

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/config.berlin.freifunk.net#52]
I just received a confirmation-mail for a freshly registered address:
```
Hey,

du hast folgende IPs bekommen:

Mesh-IPs:
 * a.f.f.e/27


Wenn du die IP-Adressen nicht mehr brauchst kannst du sie folgendem Link
löschen:



Grüße
Freifunk Berlin
```

This mail is missing the link to return the addresses, which should be printed after "folgendem Link
löschen:"

**Comment by SvenRoederer** [comment]
still broken

**Comment by Akira25** [comment]
fixed in current version. THerfore closing.

**Comment by Akira25** [comment]
Oh, I crowd too soon. While this issue seems to be fixed in standard-mode, it still persists in Expert-Mode. Got this mail:

```
Hey,

du hast folgende IPs bekommen:

Mesh-IPs:
 * 10.b.c.d/32
 * 2001:b:c:d::/56


Wenn du die IP-Adressen nicht mehr brauchst kannst du sie folgendem Link
löschen:



Grüße
Freifunk Berlin
```

**Comment by Akira25** [comment]
@rtznprmpftl
