### ISSUE TITLE
quick hack: non-expert form

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/config.berlin.freifunk.net#56]
Just to let everyone know, I changed the file /var/www/nipap-wizard on config.berlin.freifunk.net at line number 19 from
```API_POOL_HNA = 'HNA IPv4'```
to
```API_POOL_HNA = 'Mesh IPv4'```

**Comment by SvenRoederer** [comment]
Why did you change this?
Why directly on the host, rather than by the repo?

**Comment by pmelange** [comment]
The "HNA IPv4" pool is all used up.  There are still a lot of addresses free in the "Mesh IPv4" pool.  I did it on the server as a quick fix.  I also didn't quickly find how to change it in the repo.  And since @rtznprmpftl is working on moving the VM to a new setup, I put a note here.

**Comment by kls0e** [comment]
thanks for the quick fix!

**Comment by rtznprmpftl** [comment]
This is a configuration option that is tracked in the ansible repo for that host.
