### ISSUE TITLE
Expertenmodus: "kein IPv6" nicht möglich

### ISSUE THREAD

**Issue by pktpls** [freifunk-berlin/config.berlin.freifunk.net#68]
Habe im Expertenmodus IPv4 /29 und "kein IPv6" ausgewählt, die Formularvalidierung schlägt fehl: "Please select an item in the list"

**Comment by rtznprmpftl** [comment]
Fix is online, please test it

**Comment by pktpls** [comment]
Thank you very much, it fixes my bug :-)
