### ISSUE TITLE
Can't request IPv6 only

### ISSUE THREAD

**Issue by Akira25** [freifunk-berlin/config.berlin.freifunk.net#70]
In the current deployment of the service one can't request an IPv6-net only.

![grafik](https://user-images.githubusercontent.com/43141307/160274353-eb94c6c8-d12f-45e0-8c76-27377e211e91.png)

Probably related to #68.

**Comment by rtznprmpftl** [comment]
This was on purpose, since i thought that every node should have a v4 peering ip.


Do we have consensus if this should be enabled? (especially since most nodes expect the meshing partner to have a v4 address (at least to my knowledge))

**Comment by Akira25** [comment]
> This was on purpose, since i thought that every node should have a v4 peering ip.
> 
> Do we have consensus if this should be enabled? (especially since most nodes expect the meshing partner to have a v4 address (at least to my knowledge))

Sounds reasonnable to me. Closing.
