### ISSUE TITLE
"Deine Freifunk-IP-Adressen" Option is case sensitive

### ISSUE THREAD

**Issue by FFHener** [freifunk-berlin/config.berlin.freifunk.net#83]
This limit should be lifted

**Comment by nicolasberens** [comment]
i suspect this setting: https://github.com/freifunk-berlin/config.berlin.freifunk.net/blob/master/app/nipap.py#L81
wich "should" allow 2147483647 prefixes.

i temporarily set it to 512 to see if the original setting was too big

**Comment by FFHener** [comment]
The Problem i was observing wasnt a limit but rather some adresses being registerd with a Captial letter and some with a lower case letter in the beginning. Since no widely used mail systems distinguish different addresses based on case I think it would make sense to have the IP-config-wizard behave the same.

**Comment by nicolasberens** [comment]
duplicate of #47
